/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.Client
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class OPNum : TBase
  {
    private double _Num1;
    private double _Num2;

    public double Num1
    {
      get
      {
        return _Num1;
      }
      set
      {
        __isset.Num1 = true;
        this._Num1 = value;
      }
    }

    public double Num2
    {
      get
      {
        return _Num2;
      }
      set
      {
        __isset.Num2 = true;
        this._Num2 = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Num1;
      public bool Num2;
    }

    public OPNum() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Double) {
              Num1 = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              Num2 = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("OPNum");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.Num1) {
        field.Name = "Num1";
        field.Type = TType.Double;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Num1);
        oprot.WriteFieldEnd();
      }
      if (__isset.Num2) {
        field.Name = "Num2";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Num2);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("OPNum(");
      sb.Append("Num1: ");
      sb.Append(Num1);
      sb.Append(",Num2: ");
      sb.Append(Num2);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
