/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Thrift.Client
{
  public enum EnumOP
  {
    Add = 1,
    Sub = 2,
    Mult = 3,
    Div = 4,
  }
}
